FROM python:3.9-slim

RUN pip install --upgrade pip
RUN mkdir -p /app/
WORKDIR /app

COPY . /app/

RUN python3 -m pip install -r /app/requirements.txt

RUN pip3 install -r requirements.txt

EXPOSE 8501

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

COPY . .

ENTRYPOINT ["streamlit", "run", "main.py", "--server.port=8501", "--server.adress=0.0.0.0"]
